name: External Links Validator
on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    paths:
      - readme.md
      - .github/workflows/validate-external-links.yml
  schedule:
    - cron: '0 12 * * 6'
permissions:
  contents: read
  issues: write
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create an issue if needed
        if: ${{ github.event_name != 'pull_request' && failure() && steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
